spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_demo
    username: postgres
    password: 3232
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop